# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Mooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Learner')),
                ('mooclet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet')),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Variable'),
        ),
        migrations.AddField(
            model_name='value',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Version'),
        ),
        migrations.AddField(
            model_name='mooclet',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Policy'),
        ),
    ]
