# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'engine', '0001_initial'), (b'engine', '0002_auto_20170502_1920'), (b'engine', '0003_policy_policy_id'), (b'engine', '0004_auto_20170628_2319'), (b'engine', '0005_auto_20171123_0801'), (b'engine', '0006_auto_20171124_0744'), (b'engine', '0007_auto_20171213_0158'), (b'engine', '0008_auto_20171213_0201'), (b'engine', '0009_auto_20171218_0641'), (b'engine', '0004_auto_20170924_2208'), (b'engine', '0010_merge_20180103_0516'), (b'engine', '0011_auto_20180103_0649')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Mooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Learner')),
                ('mooclet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('environment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment')),
                ('variable_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet')),
                ('version_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Variable'),
        ),
        migrations.AddField(
            model_name='value',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Version'),
        ),
        migrations.AddField(
            model_name='mooclet',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Policy'),
        ),
        migrations.AddField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([('environment', 'learner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mooclet',
            unique_together=set([('environment', 'mooclet_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together=set([('environment', 'policy_id')]),
        ),
        migrations.AlterField(
            model_name='learner',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([]),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='engine_valu_mooclet_c50aaf_idx'),
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_mooclet_c50aaf_idx',
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='value_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet'], name='value_mooclet_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner'], name='value_learner_idx'),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([('environment', 'learner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mooclet',
            unique_together=set([('environment', 'mooclet_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together=set([('environment', 'policy_id')]),
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='value_primary_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='value_mooclet_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='value_learner_idx',
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([]),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='engine_valu_mooclet_c50aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet'], name='engine_valu_mooclet_78bea6_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner'], name='engine_valu_learner_00f366_idx'),
        ),
    ]
