# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
