# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
