# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_policy_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([('environment', 'learner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mooclet',
            unique_together=set([('environment', 'mooclet_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together=set([('environment', 'policy_id')]),
        ),
    ]
