# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20171123_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([]),
        ),
    ]
