# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20171213_0158'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_mooclet_c50aaf_idx',
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='value_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet'], name='value_mooclet_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner'], name='value_learner_idx'),
        ),
    ]
