# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20171213_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooclet',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
