# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20170924_2208'),
        ('engine', '0009_auto_20171218_0641'),
    ]

    operations = [
    ]
