# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 06:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20171218_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mooclet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Mooclet')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Policy')),
            ],
        ),
    ]
