# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_merge_20180103_0516'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='value',
            name='value_primary_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='value_mooclet_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='value_learner_idx',
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='mooclet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together=set([]),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='engine_valu_mooclet_c50aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet'], name='engine_valu_mooclet_78bea6_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner'], name='engine_valu_learner_00f366_idx'),
        ),
    ]
