# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 07:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_policyparameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyparameters',
            options={'verbose_name_plural': 'policyparameters'},
        ),
        migrations.AlterField(
            model_name='policyparameters',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='policyparameters',
            unique_together=set([('mooclet', 'policy')]),
        ),
    ]
