# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20180323_0735'),
        ('engine', '0011_auto_20180320_0812'),
    ]

    operations = [
    ]
