# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 08:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_merge_20180323_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
