# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_version_version_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='mooclet',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Policy'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Environment'),
        ),
        migrations.AlterField(
            model_name='value',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Learner'),
        ),
        migrations.AlterField(
            model_name='value',
            name='mooclet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Mooclet'),
        ),
        migrations.AlterField(
            model_name='value',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Policy'),
        ),
        migrations.AlterField(
            model_name='value',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Version'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Environment'),
        ),
    ]
