# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_auto_20180610_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='name',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
