# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20180927_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['learner', '-timestamp']},
        ),
        migrations.AddField(
            model_name='policyparameters',
            name='latest_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner', 'timestamp'], name='engine_valu_learner_0ec754_idx'),
        ),
    ]
