# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20181129_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['learner']},
        ),
    ]
