# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20181210_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['learner', '-timestamp']},
        ),
    ]
