# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_policyparametershistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyparametershistory',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
