# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20181228_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyparametershistory',
            options={'ordering': ['creation_time'], 'verbose_name_plural': 'policyparameterhistories'},
        ),
    ]
