# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnTaskWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField()),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='QualtricsOnTaskDataExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualtricsSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='qualtricsontaskdataexchange',
            name='data_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_exchange.QualtricsSurvey'),
        ),
        migrations.AddField(
            model_name='qualtricsontaskdataexchange',
            name='data_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_exchange.OnTaskWorkflow'),
        ),
    ]
