# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_version_version_json'),
        ('data_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualtricsontaskdataexchange',
            name='shared_variables',
            field=models.ManyToManyField(to='engine.Variable'),
        ),
    ]
