# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exchange', '0003_auto_20180610_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualtricsontaskdataexchange',
            name='shared_variables',
            field=models.ManyToManyField(blank=True, to='engine.Variable'),
        ),
    ]
