# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exchange', '0005_auto_20180610_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualtricssurvey',
            name='last_survey_respondent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
