# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_auto_20180622_0920'),
        ('data_exchange', '0007_qualtricssurvey_last_export_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualtricsontaskdataexchange',
            name='mooclets',
            field=models.ManyToManyField(blank=True, to='engine.Mooclet'),
        ),
    ]
