# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mooclet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(default='')),
                ('text_mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_mooclet.TextMooclet')),
            ],
        ),
    ]
